export const LandingVideosData = [
  {
    id: 1,
    clip: require("./assets/clip1.mp4"),
  },
  {
    id: 2,
    clip: require("./assets/clip2.mp4"),
  },
  {
    id: 3,
    clip: require("./assets/clip3.mp4"),
  },
];
export const PopularData = [
  {
    id: 1,
    title: "Nike Addapt BB",
    price: 200,
    rate: "4.5",
    img: require("./assets/popular1.png"),
    year: "2022",
    sizes: "35-38-40-45-49",
    colors: "Red - Blue - Yellow",
    orders: "6,200",
    classN: "popular-1",
  },
  {
    id: 2,
    title: "Nike Martine Rose",
    price: 220,
    rate: "5",
    img: require("./assets/popular2.png"),
    year: "2021",
    sizes: "35-38-42-45-49",
    colors: "Black - Red - Yellow",
    orders: "5,450",
    classN: "popular-2",
  },
  {
    id: 3,
    title: "Nike Smart Shoe",
    price: 150,
    rate: "4.3",
    img: require("./assets/popular3.png"),
    year: "2022",
    sizes: "33-36-43-45-49",
    colors: "Purble - White - Red",
    orders: "5,000",
    classN: "popular-3",
  },
];
export const TopSalesData = [
  {
    id: 1,
    title: "Nike Air Low Premium",
    price: 200,
    rate: "4.9",
    img: require("./assets/top1.png"),
    year: "2022",
    sizes: "33-36-43-45-49",
    colors: "Blue - White - Red",
    orders: "7,000",
    classN: "top-1",
  },
  {
    id: 2,
    title: "Nike Air Force Green",
    price: 250,
    rate: "4.7",
    img: require("./assets/top2.png"),
    year: "2020",
    sizes: "34-36-40-43-47",
    colors: "Green - Blue - Yellow",
    orders: "6.200",
    classN: "top-2",
  },
  {
    id: 3,
    title: "Nike Addapt BB Rose",
    price: 130,
    rate: "5",
    img: require("./assets/top3.png"),
    year: "2022",
    sizes: "36-40-44-49-50",
    colors: "Red - Rose - White",
    orders: "8,000",
    classN: "top-3",
  },
  {
    id: 4,
    title: "Nike Air Premium",
    price: 220,
    rate: "5",
    img: require("./assets/top4.png"),
    year: "2021",
    sizes: "33-36-43-45-49",
    colors: "Brown - Gold - White",
    orders: "4,000",
    classN: "top-4",
  },
  {
    id: 5,
    title: "Nike Adapt BB Pro",
    price: 240,
    rate: "4.8",
    img: require("./assets/top5.png"),
    year: "2021",
    sizes: "31-34-42-44-47",
    colors: "Gold - White - Blue",
    orders: "3,000",
    classN: "top-5",
  },
  {
    id: 6,
    title: "Air Jordan PR3",
    price: 140,
    rate: "4.4",
    img: require("./assets/top6.png"),
    year: "2022",
    sizes: "34-38-40-46-49",
    colors: "Blue - White - Red",
    orders: "7,000",
    classN: "top-6",
  },
  {
    id: 7,
    title: "Nike Multi Smart Shoe",
    price: 200,
    rate: "4.9",
    img: require("./assets/top7.png"),
    year: "2022",
    sizes: "33-36-43-45-49",
    colors: "Yellow - White - Blue",
    orders: "7,000",
    classN: "top-7",
  },
  {
    id: 8,
    title: "Nike Jordan Air Max",
    price: 185,
    rate: "4.6",
    img: require("./assets/top8.png"),
    year: "2022",
    sizes: "34-38-42-45-48",
    colors: "Brown - Gold - Purble",
    orders: "5,000",
    classN: "top-8",
  },
  {
    id: 9,
    title: "Nike Old Max-x",
    price: 210,
    rate: "5",
    img: require("./assets/top9.png"),
    year: "2020",
    sizes: "33-35-40-43-45",
    colors: "Blue - White - Red",
    orders: "8,000",
    classN: "top-9",
  },
  {
    id: 10,
    title: "Nike Lime Jordan 11",
    price: 170,
    rate: "5",
    img: require("./assets/top10.png"),
    year: "2022",
    sizes: "33-36-43-45-49",
    colors: "Green - Yellow - White",
    orders: "7,200",
    classN: "top-10",
  },
  {
    id: 11,
    title: "Nike Air Black Max",
    price: 200,
    rate: "4.9",
    img: require("./assets/top11.png"),
    year: "2022",
    sizes: "33-36-43-45-49",
    colors: "White - Black - Red",
    orders: "7,000",
    classN: "top-11",
  },
  {
    id: 12,
    title: "Nike Zoom Max",
    price: 250,
    rate: "5",
    img: require("./assets/top12.png"),
    year: "2021",
    sizes: "31-35-40-45-47",
    colors: "Blue - Red - Yellow",
    orders: "4,500",
    classN: "top-12",
  },
];
export const BlogsData = [
  {
    id: 1,
    img: require("./assets/blog1.jpg"),
    rate: "5",
    time: "20 Mins",
    author: "Michael Le",
    title: "Bro’s Nike Zoom Freak 4",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id deleniti distinctio quibusdam, voluptate iusto dolorem.",
  },
  {
    id: 2,
    img: require("./assets/blog2.jpg"),
    rate: "4.5",
    time: "50 Mins",
    author: "Jordan Mo",
    title: "Nike Air Max Plus",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id deleniti distinctio quibusdam, voluptate iusto dolorem.",
  },
  {
    id: 3,
    img: require("./assets/blog3.jpg"),
    rate: "4.8",
    time: "2 Hours",
    author: "Chris Joe",
    title: "Air Force 1 Low",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id deleniti distinctio quibusdam, voluptate iusto dolorem.",
  },
  {
    id: 4,
    img: require("./assets/blog4.jpg"),
    rate: "4",
    time: "1 Day",
    author: "Janet Joe",
    title: "Hello Kity NO.4",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id deleniti distinctio quibusdam, voluptate iusto dolorem.",
  },
  {
    id: 5,
    img: require("./assets/blog5.jpg"),
    rate: "4.2",
    time: "2 Days",
    author: "Josef Mo",
    title: "Jayson Tatum Debuts",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id deleniti distinctio quibusdam, voluptate iusto dolorem.",
  },
  {
    id: 6,
    img: require("./assets/blog6.jpg"),
    rate: "4.6",
    time: "2 Days",
    author: "Samuel Joe",
    title: "Air Jordan Nitro",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id deleniti distinctio quibusdam, voluptate iusto dolorem.",
  },
  {
    id: 7,
    img: require("./assets/blog7.jpg"),
    rate: "5",
    time: "4 Days",
    author: "Richard Hindi",
    title: "Bro’s Nike Air",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id deleniti distinctio quibusdam, voluptate iusto dolorem.",
  },
  {
    id: 8,
    img: require("./assets/blog8.jpg"),
    rate: "4.7",
    time: "5 Days",
    author: "Mic Anderson",
    title: "Nike Sport Shoe",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id deleniti distinctio quibusdam, voluptate iusto dolorem.",
  },
];
